export const titles = [
  {title: "スマブラ", element1: "シリーズ", element2: "イメージカラー"},
]

export const elements = [
  {img:'./img/Mario.png', name: "マリオ", element1: "スーパーマリオ", element2: "赤"},
  {img:'./img/DonkeyKong.png', name: "ドンキーコング", element1: "ドンキーコング", element2: "茶"},
  {img:'./img/Link.png', name: "リンク", element1: "ゼルダの伝説", element2: "青"},
  {img:'./img/Samus.png', name: "サムス", element1: "METROID", element2: "茶"},
  {img:'./img/darksum.png', name: "ダークサムス", element1: "METROID", element2: "黒"},
  {img:'./img/Yoshi.png', name: "ヨッシー", element1: "YOSHI", element2: "緑"},
  {img:'./img/Kirby.png', name: "カービー", element1: "星のカービー", element2: "ピンク"},
  {img:'./img/Fox.png', name: "フォックス", element1: "START FOX", element2: "茶"},
  {img:'./img/Pikachu.png', name: "ピカチュウ", element1: "ポケモン", element2: "黄"},
  {img:'./img/Luigi.png', name: "ルイージ", element1: "スーパーマリオ", element2: "緑"},
  {img:'./img/Nes.png', name: "ネス", element1: "MOTHER", element2: ""},
  {img:'./img/Falcon.png', name: "キャプテン・ファルコン", element1: "F-ZERO", element2: "青"},
  {img:'./img/Purin.png', name: "プリン", element1: "ポケモン", element2: "ピンク"},
  {img:'./img/Peach.png', name: "ピーチ", element1: "スーパーマリオ", element2: "ピンク"},
  {img:'./img/Daisy.png', name: "デイジー", element1: "スーパーマリオ", element2: "茶"},
  {img:'./img/Copper.png', name: "クッパ", element1: "スーパーマリオ", element2: ""},
  {img:'./img/Ice.png', name: "アイスクライマー", element1: "アイスクライマー", element2: "白"},
  {img:'./img/Seak.png', name: "シーク", element1: "ゼルダの伝説", element2: "青"},
  {img:'./img/Zelda.png', name: "ゼルダ", element1: "ゼルダの伝説", element2: "ピンク"},
  {img:'./img/DocktorMario.png', name: "ドクターマリオ", element1: "スーパーマリオ", element2: "白"},
  {img:'./img/pichu.png', name: "ピチュー", element1: "ポケモン", element2: "黄"},
  {img:'./img/Falco.png', name: "ファルコ", element1: "START FOX", element2: "青"},
  {img:'./img/Marus.png', name: "マルス", element1: "ファイアーエンブレム", element2: "青"},
  {img:'./img/lucina.png', name: "ルキナ", element1: "ファイアーエンブレム", element2: "青"},
  {img:'./img/YaungLink.png', name: "ヤングリンク", element1: "ゼルダの伝説", element2: "緑"},
  {img:'./img/ganon.png', name: "ガノンドルフ", element1: "ゼルダの伝説", element2: "赤"},
  {img:'./img/myutwo.png', name: "ミューツー", element1: "ポケモン", element2: "白"},
  {img:'./img/roi.png', name: "ロイ", element1: "ファイアーエンブレム", element2: "赤"},
  {img:'./img/kuromu.png', name: "クロム", element1: "ファイアーエンブレム", element2: "黒"},
  {img:'./img/mrgw.png', name: "Mr.Game&Watch", element1: "Game&Watch", element2: "黒"},
  {img:'./img/metanaito.png', name: "メタナイト", element1: "星のカービー", element2: ""},
  {img:'./img/pit.png', name: "ピット", element1: "光神話 パルテナの鏡", element2: "白"},
  {img:'./img/burapi.png', name: "ブラックピット", element1: "光神話 パルテナの鏡", element2: "黒"},
  {img:'./img/zerosam.png', name: "ゼロスーツサムス", element1: "METROID", element2: "青"},
  {img:'./img/wrio.png', name: "ワリオ", element1: "メイド イン ワリオ", element2: "黄"},
  {img:'./img/sneak.png', name: "スネーク", element1: "METAL GEAR", element2: "黒"},
  {img:'./img/ike.png', name: "アイク", element1: "ファイアーエンブレム", element2: "赤"},
  {img:'./img/poketore.png', name: "ポケモントレーナー", element1: "ポケモン", element2: ["青", "緑", "赤"]},
  {img:'./img/dd.png', name: "ディーディーコング", element1: "ドンキーコング", element2: "茶"},
  {img:'./img/ryocas.png', name: "リュカ", element1: "MOTHER", element2: "黄"},
  {img:'./img/sonic.png', name: "ソニック", element1: "SONIC", element2: "青"},
  {img:'./img/dedede.png', name: "デデデ", element1: "星のカービー", element2: "赤"},
  {img:'./img/pikumin.png', name: "ピクミン＆ウォリマー", element1: "ピクミン", element2: ["赤", "青", "黄"]},
  {img:'./img/rukario.png', name: "ルカリオ", element1: "ポケモン", element2: "青"},
  {img:'./img/robot.png', name: "ロボット", element1: "ROBOT", element2: "白"},
  {img:'./img/tounlink.png', name: "トゥーンリンク", element1: "ゼルダの伝説", element2: "緑"},
  {img:'./img/uruhu.png', name: "ウルフ", element1: "START FOX", element2: "黒"},
  {img:'./img/murabito.png', name: "村人", element1: "どうぶつの森", element2: ""},
  {img:'./img/rockman.png', name: "ロックマン", element1: "ROCKMAN", element2: "青"},
  {img:'./img/wiifit.png', name: "Wii Fit トレーナー", element1: "Wii Fit", element2: "白"},
  {img:'./img/rozeta.png', name: "ロゼッタ&チコ", element1: "スーパーマリオ", element2: ["青", "黄"]},
  {img:'./img/littlemac.png', name: "リトルマック", element1: "PUNCH-OUT", element2: "緑"},
  {img:'./img/gekko.png', name: "ゲッコウガ", element1: "ポケモン", element2: "青"},
  {img:'./img/mii.png', name: "Mii ファイター", element1: "Mii", element2: ["赤", "青", "黄"]},
  {img:'./img/pal.png', name: "パルテナ", element1: "光神話 パルテナの鏡", element2: "緑"},
  {img:'./img/packman.png', name: "パックマン", element1: "PAC-MAN", element2: "黄"},
  {img:'./img/luhure.png', name: "ルフレ", element1: "ファイアーエンブレム", element2: ""},
  {img:'./img/shuruku.png', name: "シュルク", element1: "Xenoblade", element2: "赤"},
  {img:'./img/jr.png', name: "クッパJr.", element1: "スーパーマリオ", element2: ""},
  {img:'./img/dackhanto.png', name: "ドックハント", element1: "DUCK HUNT", element2: "茶"},
  {img:'./img/ryu.png', name: "リュウ", element1: "STREET FIGHTER", element2: "赤"},
  {img:'./img/ken.png', name: "ケン", element1: "STREET FIGHTER", element2: "赤"},
  {img:'./img/cloud.png', name: "クラウド", element1: "FINAL FANTASY", element2: "黒"},
  {img:'./img/kamui.png', name: "カムイ", element1: "ファイアーエンブレム", element2: "白"},
  {img:'./img/beyo.png', name: "ベヨネッタ", element1: "BAYONETA", element2: "黒"},
  {img:'./img/inku.png', name: "インクリング", element1: "Splatoon", element2: ["赤", "青", "緑", "黄"]},
  {img:'./img/ridori.png', name: "リドリー", element1: "METROID", element2: "黒"},
  {img:'./img/simon.png', name: "シモン", element1: "悪魔城 ドラキュラ", element2: "茶"},
  {img:'./img/lihitar.png', name: "リヒター", element1: "悪魔城 ドラキュラ", element2: "青"},
  {img:'./img/kingcluru.png', name: "キングクルール", element1: "ドンキーコング", element2: "緑"},
  {img:'./img/sizue.png', name: "しずえ", element1: "どうぶつの森", element2: "黄"},
  {img:'./img/gaogaen.png', name: "ガオガエン", element1: "ポケモン", element2: "赤"},
  {img:'./img/packnfl.png', name: "パックンフラワー", element1: "スーパーマリオ", element2: "赤"},
  {img:'./img/joker.png', name: "ジョーカー", element1: "PERSONA5", element2: "黒"},
  {img:'./img/yusha.png', name: "勇者", element1: "DRAGON QUEST", element2: ""},
  {img:'./img/banjo.png', name: "バンジョー＆カズーイ", element1: "バンジョーとカズーイの大冒険", element2: ["茶", "赤"]},
  {img:'./img/tely.png', name: "テリー", element1: "餓狼伝説", element2: "赤"},
  {img:'./img/bereto.png', name: "ベレト/ベレズ", element1: "ファイアーエンブレム", element2: "青"},
  {img:'./img/myenmyen.png', name: "ミェンミェン", element1: "ARMS", element2: "黄"},
];
// DB構造終了
