export const titles = [
  {title: "スマブラ",},
]

export const roles = [
  {name: "スーパーマリオ", contain: ["マリオ", "ルイージ", "ピーチ", "デイジー", "クッパ","ドクターマリオ","ロゼッタ&チコ","クッパJr.","パックンフラワー",]},
  {name: "ドンキーコング", contain: ["ドンキーコング", "ディーディーコング", "キングクルール",]},
  {name: "ゼルダの伝説", contain: ["リンク", "シーク", "ゼルダ","ヤングリンク", "ガノンドルフ","トゥーンリンク",]},
  {name: "METROID", contain: ["サムス", "ダークサムス", "ゼロスーツサムス","リドリー",]},
  {name: "星のカービー", contain: ["カービー", "メタナイト", "デデデ",]},
  {name: "STAR FOX", contain: ["フォックス", "ファルコ", "ウルフ",]},
  {name: "ポケモン", contain: ["ピカチュー", "プリン", "ピチュー","ミューツー", "ポケモントレーナー", "ルカリオ", "ゲッコウガ", "ガオガエン"]},
  {name: "MOTHER", contain: ["ネス", "リュカ",]},
  {name: "ファイアーエンブレム", contain: ["マルス", "ルキナ","ロイ", "クロム", "アイク", "ルフレ", "カムイ", "ベレト/ベレズ"]},
  {name: "光神話 パルテナの鏡", contain: ["ピット", "ブラックピット","パルテナ",]},
  {name: "どうぶつの森", contain: ["むらびと", "しずえ",]},
  {name: "STREET FIGHTER", contain: ["リュウ", "ケン",]},
  {name: "悪魔城 ドラキュラ", contain: ["シモン", "リヒター",]},

  {name: "剣キャラ", contain: ["リンク","マルス", "ルキナ","ロイ", "クロム", "アイク", "ルフレ", "カムイ", "ベレト/ベレズ", "シュルク", "クラウド", "勇者"]},
  {name: "小型 剣キャラ", contain: ["メタナイト","ヤングリンク","トゥーンリンク", "Mii ファイター"]},

  {name: "重量級", contain: ["クッパ","キングクルール","ドンキーコング", "デデデ", "ガノンドルフ", "ガオガエン", "ポケモントレーナー"]},
  {name: "軽量級", contain: ["カービー","ピカチュウ","プリン", "Mr.Game&Watch", "シーク", "ピチュー", "ミューツー", "ピクミン＆ウォリマー", "フォックス", "ポケモントレーナー"]},

  {name:"多段ジャンプ", contain: ["カービー", "メタナイト", "ピット", "ブラックピット", "ポケモントレーナー", "デデデ", "プリン", "リドリー",]},
  {name:"カベはりつき", contain: ["シーク", "ディーディーコング", "ルカリオ", "ベヨネッタ", "ポケモントレーナー",]},
]

export const cards = [
  {img:'./img/Mario.png', name: "マリオ",},
  {img:'./img/DonkeyKong.png', name: "ドンキーコング",},
  {img:'./img/Link.png', name: "リンク",},
  {img:'./img/Samus.png', name: "サムス",},
  {img:'./img/darksum.png', name: "ダークサムス",},
  {img:'./img/Yoshi.png', name: "ヨッシー",},
  {img:'./img/Kirby.png', name: "カービー",},
  {img:'./img/Fox.png', name: "フォックス",},
  {img:'./img/Pikachu.png', name: "ピカチュウ",},
  {img:'./img/Luigi.png', name: "ルイージ",},
  {img:'./img/Nes.png', name: "ネス",},
  {img:'./img/Falcon.png', name: "キャプテン・ファルコン",},
  {img:'./img/Purin.png', name: "プリン",},
  {img:'./img/Peach.png', name: "ピーチ",},
  {img:'./img/Daisy.png', name: "デイジー",},
  {img:'./img/Copper.png', name: "クッパ",},
  {img:'./img/Ice.png', name: "アイスクライマー",},
  {img:'./img/Seak.png', name: "シーク",},
  {img:'./img/Zelda.png', name: "ゼルダ",},
  {img:'./img/DocktorMario.png', name: "ドクターマリオ",},
  {img:'./img/pichu.png', name: "ピチュー",},
  {img:'./img/Falco.png', name: "ファルコ",},
  {img:'./img/Marus.png', name: "マルス",},
  {img:'./img/lucina.png', name: "ルキナ",},
  {img:'./img/YaungLink.png', name: "ヤングリンク",},
  {img:'./img/ganon.png', name: "ガノンドルフ",},
  {img:'./img/myutwo.png', name: "ミューツー",},
  {img:'./img/roi.png', name: "ロイ",},
  {img:'./img/kuromu.png', name: "クロム",},
  {img:'./img/mrgw.png', name: "Mr.Game&Watch",},
  {img:'./img/metanaito.png', name: "メタナイト",},
  {img:'./img/pit.png', name: "ピット",},
  {img:'./img/burapi.png', name: "ブラックピット",},
  {img:'./img/zerosam.png', name: "ゼロスーツサムス",},
  {img:'./img/wrio.png', name: "ワリオ",},
  {img:'./img/sneak.png', name: "スネーク",},
  {img:'./img/ike.png', name: "アイク",},
  {img:'./img/poketore.png', name: "ポケモントレーナー",},
  {img:'./img/dd.png', name: "ディーディーコング",},
  {img:'./img/ryocas.png', name: "リュカ",},
  {img:'./img/sonic.png', name: "ソニック",},
  {img:'./img/dedede.png', name: "デデデ",},
  {img:'./img/pikumin.png', name: "ピクミン＆ウォリマー",},
  {img:'./img/rukario.png', name: "ルカリオ",},
  {img:'./img/robot.png', name: "ロボット",},
  {img:'./img/tounlink.png', name: "トゥーンリンク",},
  {img:'./img/uruhu.png', name: "ウルフ",},
  {img:'./img/murabito.png', name: "むらびと",},
  {img:'./img/rockman.png', name: "ロックマン",},
  {img:'./img/wiifit.png', name: "Wii Fit トレーナー",},
  {img:'./img/rozeta.png', name: "ロゼッタ&チコ",},
  {img:'./img/littlemac.png', name: "リトルマック",},
  {img:'./img/gekko.png', name: "ゲッコウガ",},
  {img:'./img/mii.png', name: "Mii ファイター",},
  {img:'./img/pal.png', name: "パルテナ",},
  {img:'./img/packman.png', name: "パックマン",},
  {img:'./img/luhure.png', name: "ルフレ",},
  {img:'./img/shuruku.png', name: "シュルク",},
  {img:'./img/jr.png', name: "クッパJr.",},
  {img:'./img/dackhanto.png', name: "ドックハント",},
  {img:'./img/ryu.png', name: "リュウ",},
  {img:'./img/ken.png', name: "ケン",},
  {img:'./img/cloud.png', name: "クラウド",},
  {img:'./img/kamui.png', name: "カムイ",},
  {img:'./img/beyo.png', name: "ベヨネッタ",},
  {img:'./img/inku.png', name: "インクリング",},
  {img:'./img/ridori.png', name: "リドリー",},
  {img:'./img/simon.png', name: "シモン",},
  {img:'./img/lihitar.png', name: "リヒター",},
  {img:'./img/kingcluru.png', name: "キングクルール",},
  {img:'./img/sizue.png', name: "しずえ",},
  {img:'./img/gaogaen.png', name: "ガオガエン",},
  {img:'./img/packnfl.png', name: "パックンフラワー",},
  {img:'./img/joker.png', name: "ジョーカー",},
  {img:'./img/yusha.png', name: "勇者",},
  {img:'./img/banjo.png', name: "バンジョー＆カズーイ",},
  {img:'./img/tely.png', name: "テリー",},
  {img:'./img/bereto.png', name: "ベレト/ベレズ",},
  {img:'./img/myenmyen.png', name: "ミェンミェン",},
];
// DB構造終了
