export const elements = [
  {img:'./img/Mario.png', name: "マリオ", series: "スーパーマリオ", color: "赤"},
  {img:'./img/DonkeyKong.png', name: "ドンキーコング", series: "ドンキーコング", color: "茶"},
  {img:'./img/Link.png', name: "リンク", series: "ゼルダの伝説", color: "青"},
  {img:'./img/Samus.png', name: "サムス", series: "METROID", color: "茶"},
  {img:'./img/darksum.png', name: "ダークサムス", series: "METROID", color: "黒"},
  {img:'./img/Yoshi.png', name: "ヨッシー", series: "YOSHI", color: "緑"},
  {img:'./img/Kirby.png', name: "カービー", series: "星のカービー", color: "ピンク"},
  {img:'./img/Fox.png', name: "フォックス", series: "START FOX", color: "茶"},
  {img:'./img/Pikachu.png', name: "ピカチュウ", series: "ポケモン", color: "黄"},
  {img:'./img/Luigi.png', name: "ルイージ", series: "スーパーマリオ", color: "緑"},
  {img:'./img/Nes.png', name: "ネス", series: "MOTHER", color: ""},
  {img:'./img/Falcon.png', name: "キャプテン・ファルコン", series: "F-ZERO", color: "青"},
  {img:'./img/Purin.png', name: "プリン", series: "ポケモン", color: "ピンク"},
  {img:'./img/Peach.png', name: "ピーチ", series: "スーパーマリオ", color: "ピンク"},
  {img:'./img/Daisy.png', name: "デイジー", series: "スーパーマリオ", color: "茶"},
  {img:'./img/Copper.png', name: "クッパ", series: "スーパーマリオ", color: ""},
  {img:'./img/Ice.png', name: "アイスクライマー", series: "アイスクライマー", color: "白"},
  {img:'./img/Seak.png', name: "シーク", series: "ゼルダの伝説", color: "青"},
  {img:'./img/Zelda.jpg', name: "ゼルダ", series: "ゼルダの伝説", color: "ピンク"},
  {img:'./img/DocktorMario.png', name: "ドクターマリオ", series: "スーパーマリオ", color: "白"},
  {img:'./img/pichu.png', name: "ピチュー", series: "ポケモン", color: "黄"},
  {img:'./img/Falco.png', name: "ファルコ", series: "START FOX", color: "青"},
  {img:'./img/Marus.png', name: "マルス", series: "ファイアーエンブレム", color: "青"},
  {img:'./img/lucina.png', name: "ルキナ", series: "ファイアーエンブレム", color: "青"},
  {img:'./img/YaungLink.png', name: "ヤングリンク", series: "ゼルダの伝説", color: "緑"},
  {img:'./img/ganon.png', name: "ガノンドルフ", series: "ゼルダの伝説", color: "赤"},
  {img:'./img/myutwo.png', name: "ミューツー", series: "ポケモン", color: "白"},
  {img:'./img/roi.png', name: "ロイ", series: "ファイアーエンブレム", color: "赤"},
  {img:'./img/kuromu.png', name: "クロム", series: "ファイアーエンブレム", color: "黒"},
  {img:'./img/mrgw.png', name: "Mr.Game&Watch", series: "Game&Watch", color: "黒"},
  {img:'./img/metanaito.png', name: "メタナイト", series: "星のカービー", color: ""},
  {img:'./img/pit.png', name: "ピット", series: "光神話 パルテナの鏡", color: "白"},
  {img:'./img/burapi.png', name: "ブラックピット", series: "光神話 パルテナの鏡", color: "黒"},
  {img:'./img/zerosam.png', name: "ゼロスーツサムス", series: "METROID", color: "青"},
  {img:'./img/wrio.png', name: "ワリオ", series: "メイド イン ワリオ", color: "黄"},
  {img:'./img/sneak.png', name: "スネーク", series: "METAL GEAR", color: "黒"},
  {img:'./img/ike.png', name: "アイク", series: "ファイアーエンブレム", color: "赤"},
  {img:'./img/poketore.png', name: "ポケモントレーナー", series: "ポケモン", color: ["青", "緑", "赤"]},
  {img:'./img/dd.jpeg', name: "ディーディーコング", series: "ドンキーコング", color: "茶"},
  {img:'./img/ryocas.png', name: "リュカ", series: "MOTHER", color: "黄"},
  {img:'./img/sonic.png', name: "ソニック", series: "SONIC", color: "青"},
  {img:'./img/dedede.png', name: "デデデ", series: "星のカービー", color: "赤"},
  {img:'./img/pikumin.png', name: "ピクミン＆ウォリマー", series: "ピクミン", color: ["赤", "青", "黄"]},
  {img:'./img/rukario.png', name: "ルカリオ", series: "ポケモン", color: "青"},
  {img:'./img/robot.png', name: "ロボット", series: "ROBOT", color: "白"},
  {img:'./img/tounlink.png', name: "トゥーンリンク", series: "ゼルダの伝説", color: "緑"},
  {img:'./img/uruhu.png', name: "ウルフ", series: "START FOX", color: "黒"},
  {img:'./img/murabito.png', name: "村人", series: "どうぶつの森", color: ""},
  {img:'./img/rockman.png', name: "ロックマン", series: "ROCKMAN", color: "青"},
  {img:'./img/wiifit.png', name: "Wii Fit トレーナー", series: "Wii Fit", color: "白"},
  {img:'./img/rozeta.png', name: "ロゼッタ&チコ", series: "スーパーマリオ", color: ["青", "黄"]},
  {img:'./img/littlemac.png', name: "リトルマック", series: "PUNCH-OUT", color: "緑"},
  {img:'./img/gekko.png', name: "ゲッコウガ", series: "ポケモン", color: "青"},
  {img:'./img/mii.png', name: "Mii ファイター", series: "Mii", color: ["赤", "青", "黄"]},
  {img:'./img/pal.png', name: "パルテナ", series: "光神話 パルテナの鏡", color: "緑"},
  {img:'./img/packman.jpeg', name: "パックマン", series: "PAC-MAN", color: "黄"},
  {img:'./img/luhure.png', name: "ルフレ", series: "ファイアーエンブレム", color: ""},
  {img:'./img/shuruku.png', name: "シュルク", series: "Xenoblade", color: "赤"},
  {img:'./img/jr.png', name: "クッパJr.", series: "スーパーマリオ", color: ""},
  {img:'./img/dackhanto.png', name: "ドックハント", series: "DUCK HUNT", color: "茶"},
  {img:'./img/ryu.png', name: "リュウ", series: "STREET FIGHTER", color: "赤"},
  {img:'./img/ken.png', name: "ケン", series: "STREET FIGHTER", color: "赤"},
  {img:'./img/cloud.png', name: "クラウド", series: "FINAL FANTASY", color: "黒"},
  {img:'./img/kamui.png', name: "カムイ", series: "ファイアーエンブレム", color: "白"},
  {img:'./img/beyo.png', name: "ベヨネッタ", series: "BAYONETA", color: "黒"},
  {img:'./img/inku.png', name: "インクリング", series: "Splatoon", color: "赤"},
  {img:'./img/ridori.png', name: "リドリー", series: "METROID", color: "黒"},
  {img:'./img/simon.png', name: "シモン", series: "悪魔城 ドラキュラ", color: "茶"},
  {img:'./img/lihitar.png', name: "リヒター", series: "悪魔城 ドラキュラ", color: "青"},
  {img:'./img/kingcluru.png', name: "キングクルール", series: "ドンキーコング", color: "緑"},
  {img:'./img/sizue.png', name: "しずえ", series: "どうぶつの森", color: "黄"},
  {img:'./img/gaogaen.png', name: "ガオガエン", series: "ポケモン", color: "赤"},
  {img:'./img/packnfl.png', name: "パックンフラワー", series: "スーパーマリオ", color: "赤"},
  {img:'./img/joker.png', name: "ジョーカー", series: "PERSONA5", color: "黒"},
  {img:'./img/yusha.png', name: "勇者", series: "DRAGON QUEST", color: ""},
  {img:'./img/banjo.png', name: "バンジョー＆カズーイ", series: "バンジョーとカズーイの大冒険", color: ["茶", "赤"]},
  {img:'./img/tely.png', name: "テリー", series: "餓狼伝説", color: "赤"},
  {img:'./img/bereto.png', name: "ベレト/ベレズ", series: "ファイアーエンブレム", color: "青"},
  {img:'./img/myenmyen.jpg', name: "ミェンミェン", series: "ARMS", color: "黄"},
];
// DB構造終了
